# Docker-Compose Version
version: '3.9'
name: 'tug-logistics-api-platform'
services:
    tug-logistics-api:
        build:
            context: ./
            dockerfile: docker/local.Dockerfile
        restart: unless-stopped
        working_dir: /var/www
        tty: true
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
        networks:
            - my-network
volumes:
    mysql-data:
# Networks
networks:
    my-network:
        driver: bridge
